In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim) #the function of ndim is to return the 
#interger that tells us how many dimensions the array have

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [14]:
#checking the numpy version
import numpy as np
print(np.__version__)
arr=np.array((1,2,3))
print(arr)
print(arr.ndim)

2.4.2
[1 2 3]
1


In [15]:
#creating 0-D array with the value 42
#0-D arrays or scalars are the elements in an array
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [16]:
#creating 1-D array containing apple ,mango
#this is the array which has 0-D arrays as its elements
#AKA uni-dimensional array
import numpy as np
arr=np.array(['apple','mango'])
print(arr)
print(arr.ndim)

['apple' 'mango']
1


In [17]:
#creating a 2D array containing 2 arrays with the values
#1,2,3 and 4,5,6
#this is the array which has 1D arrays as its elements
#they are often used to represent matrix or 2nd order tensors.
import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [18]:
#creating 3D array with 2D arrays, both containing two 
#arrays with values 1,2,3 and 4,5,6
#this is the array that has 2D arrays(matrices) as its elements

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
#higher dimension, an array can have any no. of dimensions
#creating an array with 5 dimensions and verify that it
# has 5 dimesions

import numpy as np
arr=np.array([1,2,3,4,5,6,7],ndmin=5) #dont get confused
# here we should use ndmin not ndim OK
print(arr)
print("the number of dimesions:",arr.ndim) 

[[[[[1 2 3 4 5 6 7]]]]]
the number of dimesions: 5


In [ ]:
#array indexing
import numpy as np
arr=np.array([2,24,3,32])
print(arr[0],arr[3])
print(arr[1]+arr[2])#to find the sum of elements in an array


2 32
27


In [26]:
#accessing 2D array
#accessing the elements on the first row, second column
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("2nd element on the 1st row is: ",arr[0,1])
print("2nd row , third column: ",arr[1,2])

[[1 2 3 4]
 [5 6 7 8]]
2nd element on the 1st row is:  2
2nd row , third column:  7


In [41]:
#accessing 3D array
import numpy as np
arr=np.array([[[1,2,3,4],[9,8,6,0]],[[5,6,7,8],[33,44,56,89]]])
print(arr)
print("\n")
print("accessing third element of the second array of the first array: "
      ,arr[0,1,2])
print(" 2nd array ko 2nd array ko 3rd element: ",arr[1,1,2])

[[[ 1  2  3  4]
  [ 9  8  6  0]]

 [[ 5  6  7  8]
  [33 44 56 89]]]


accessing third element of the second array of the first array:  6
 2nd array ko 2nd array ko 3rd element:  56


In [44]:
#negative indexing
#we use negative indexing in order to access an array from the end
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('last element from 2nd dimension:',arr[1,-1])
print('3rd last element from 1st dim:', arr[0,-3])

last element from 2nd dimension: 8
3rd last element from 1st dim: 2


In [ ]:
#numpy array slicing
#slice elements from index 1 to index 5 
import numpy as np
arr=np.array([1,2,3,4,9,6]) #index here starts with 1 not 0
print(arr[1:5])

[2 3 4 9]


In [4]:
#slicing elements from index 4 to the end of the array
import numpy as np
arr=np.array([1,2,3,45,5,55,43,34])
print(arr[4:])

[ 5 55 43 34]


In [7]:
#slicling the elements from the begining to the index 4
import numpy as np
arr=np.array([1,2,3,4,56,75])
print(arr[:4])

[1 2 3 4]


In [8]:
#negative slicing
#slicing the elements from the index 3 from the end to index 1 from the end
import numpy as np
arr=np.array([1,2,3,4,5,3,22,32,234,242,42])
print(arr[-3:-1])

[234 242]


In [14]:
#we use 'step' value to determine the step of the slicing
import numpy as np
arr=np.array([1,6,9,3,4,24,52,24,242])
print(arr[1:6:2]) #returning every other element from index 1 to 6


[ 6  3 24]


In [12]:
#returning every other element from the entire array
import numpy as np
arr=np.array([1,2,3,45,65,32,2,7,8])
print(arr[::2])

[ 1  3 65  2  8]


In [18]:
#slicing 2D arrays
#from the second element, slicing elements from index 1 to 4
import numpy as np
arr=np.array([[1,2,3,4],[5,6,78,8]])
print(arr[1,1:4])

#from both elements, return index 2
print(arr[0:2,2]) #or you can simply do :2 both same

#from both elements, slice index 1 to 4 
print(arr[:2,1:4])

[ 6 78  8]
[ 3 78]
[[ 2  3  4]
 [ 6 78  8]]


In [28]:
#to find the datatype of an array, we use 'dtype' property
import numpy as np
arr=np.array([1,2,3,44,4.5])
print(arr.dtype)
arr=np.array(['cat','dog'])
print(arr.dtype)

float64
<U3


In [34]:
#creating arrays with a defined datatypes
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)
#for i,u,f,S,U we can define size as well
prr=np.array([1,2,3,4],dtype='i8')
print(prr)
print(prr.dtype)


[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int64


In [39]:
#to convert the datatype on existing arrays we use astype()
import numpy as np
arr=np.array([1.2,1.4,6.5,8.6])
newarr=arr.astype('i') #or you can simply use int instead of i, to change to integer ,use bool
print(newarr)
print(newarr.dtype)

[1 1 6 8]
int32


In [ ]:
#numpy array copy vs view
#make a copy,change the original array and display both
import numpy as np
arr=np.array([2,2,3,4])
x=arr.copy()
arr[0]=43
print(arr)
print(x)
#here the copy of an array is not affected by the changes made to the original array

[43  2  3  4]
[2 2 3 4]


In [ ]:
#make a view, change the original array and display both
import numpy as np
arr=np.array([4,6,75,3,2])
z=arr.view()
arr[3]=44
z[1]=23
print(arr)
print(z)
#here the view is affected by the changes made to the original array
#and the original array is also affected by the changes made to the view


[ 4 23 75 44  2]
[ 4 23 75 44  2]


In [ ]:
#checking if the array owns its data, for this we use
#base attribute which returns None if the array owns the data
import numpy as np
arr=np.array([1,23,4,2,6,7])
x=arr.copy()
z=arr.view()
print(x.base)
print(z.base)
#from the output we can be cleared that copy owns the data and views doesnot


None
[ 1 23  4  2  6  7]


In [50]:
#shape of an array is the no. of elements in each dimension
#printing the shape of a 2D array
import numpy as np
arr=np.array([[1,2,3,6,4],[6,7,8,9,3],[3,2,4,2,5]])
print(arr)
print(arr.shape)

[[1 2 3 6 4]
 [6 7 8 9 3]
 [3 2 4 2 5]]
(3, 5)


In [52]:
#creating an array with 5 dimensions using ndmin
import numpy as np
arr=np.array([[1,2,3,4],[4,6,7,8]],ndmin=5)
print(arr)
print('shape of array: ',arr.shape)

[[[[[1 2 3 4]
    [4 6 7 8]]]]]
shape of array:  (1, 1, 1, 2, 4)


In [ ]:
#numpy array reshaping,we use reshape module
#converting 1D array with 12 elements into 2D array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,11,22,34])
newarr=arr.reshape(4,3)
print(newarr)
print("\n")

#reshaping into 3Darray
threeD=arr.reshape(2,3,2)#the outermost dimension will have
#2 arrays that contains 3 arrays,each with 2 elements
print(threeD)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 34]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 11]
  [22 34]]]


In [ ]:
#checking if the returned array is a copy or a view
print(arr.reshape(2,6).base)
#the output is the original array which means it is a view


[ 1  2  3  4  5  6  7  8  9 11 22 34]


In [6]:
#unknown dimension
#converting 1D array with 8 elements to 3Darray with 2x2 elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#flattening the arrays, we use reshape(-1)
#it means converting the multidimensional array into a 1D array

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [10]:
#iterating arrays, it means going through elements one by one
#iterating on the elements of 1D array
import numpy as p
arr=p.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
#iterating 2D array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    #if we iterate on n-D array it will go through n-1th
    #dimension one by one

[1 2 3]
[4 5 6]


In [12]:
#iterating on each scalar element of the 2D array
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [15]:
#iterating on the elements of 3D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [17]:
#iterating down to the scalars i.e actual values
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
#iterating arrays using nditer()
#we use it in order to make iterating easier because when
#we have to loop through elements with very high dimensionality
#we need 'n' for loops which can be difficult to write, so we use it
 
import numpy as np
arr=np.array([[[1,2],[3,4]],[[4,5],[6,7]]]) #iterate through each scalar elements
for x in np.nditer(arr):
    print(x)

1
2
3
4
4
5
6
7


In [21]:
#iterating array with different datatypes,
#we use op_dtypes argument and pass it the expected datatype

#iterate through each array as a string
import numpy as np
arr=np.array([1,2,3,4])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [27]:
#iterating through each scalar element of the 2D array skipping 1 element
import numpy as np
arr=np.array([[1,23,0],[4,3,2]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
0
4
2


In [ ]:
#enumerated iteration using ndenumerate()
#enumerating on 1D arrays elements
import numpy as np
arr=np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx,x) 
 #enumeration means mentioning sequence number of something 1 by 1
#we use this function inorder to show the corresponding index of the element while iterating


(0,) 1
(1,) 2
(2,) 3


In [29]:
#enumerating 2D arrays elements
import numpy as np
arr=np.array([[1,2,3,4],[7,8,68,9]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 7
(1, 1) 8
(1, 2) 68
(1, 3) 9


In [2]:
#joining two arrays, we use concatenate() function
import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate([arr1,arr2])
print(arr)

[1 2 3 4 5 6]


In [3]:
#joining 2D array along rows (axis=1)
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[33,45,2]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 33 45  2]]


In [11]:
#joining arrays using stack function
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

#to stack along the rows ,we use hstack() function
arr=np.hstack((arr1,arr2))
print(arr)

#to stack along the columns, we use vstack() function
arr=np.vstack((arr1,arr2))
print(arr)

#to stack along the height , we use dstack() function
arr=np.dstack((arr1,arr2))
print(arr)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [18]:
#splitting the array, we use array_split() function
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)
print(newarr[0])
print(newarr[2])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [30]:
#splitting 2D array into three 2D arrays
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[7,5]])
print((np.array_split(arr,3)))
print((np.hsplit(arr,2)))#splitting along columns

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [ 7,  5]])]
[array([[1],
       [3],
       [5],
       [7],
       [9],
       [7]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 5]])]


In [ ]:
#lets do with 3 elements in each array
arr=np.array([[1,2,4],[3,4,5],[5,6,3],[7,8,5],[9,10,6],[7,5,66]])
print((np.array_split(arr,3)))

#splitting 2D array into three 2D arrays along columns
arr=np.array([[1,2,4],[3,4,5],[5,6,3],[7,8,5],[9,10,6],[7,5,66]])
print((np.array_split(arr,3,axis=1))) #we can also use hsplit() opposite of hstack()
#similarly we can use vsplit and dsplit() for splitting along 
#rows and height

[array([[1, 2, 4],
       [3, 4, 5]]), array([[5, 6, 3],
       [7, 8, 5]]), array([[ 9, 10,  6],
       [ 7,  5, 66]])]
[array([[1],
       [3],
       [5],
       [7],
       [9],
       [7]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 5]]), array([[ 4],
       [ 5],
       [ 3],
       [ 5],
       [ 6],
       [66]])]


In [35]:
#searching array, we use where() method
#searching indexes where the value is 4
import numpy as np
arr=np.array([1,2,3,4,5,3,2,4,4])
x=np.where(arr==4)
print(x)

#search the indexes where the values are even
print((np.where(arr%2==0)))
#for odd
print((np.where(arr%2==1)))


(array([3, 7, 8]),)
(array([1, 3, 6, 7, 8]),)
(array([0, 2, 4, 5]),)


In [42]:
#search sorted, we use searchsorted() method
#find the indexes where the value 7 should be inserted
import numpy as np
arr=np.array([6,7,8,5])
x=np.searchsorted(arr,7)
print(x)
#what if
x=np.searchsorted(arr,5)
print(x)
#by default it is searched from left but what if we want to search from right
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

1
0
2


In [45]:
#find the indexes where the values 2,4 and 6 should be inserted
import numpy as np
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


In [3]:
#numpy arrays sorting, we use sort() function
import numpy as np
arr=np.array([1,4,0,2])
print(np.sort(arr))
#sorting array alphabetically
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))
#sorting a boolean array
arr=np.array(['true','false','true'])
print(np.sort(arr))

[0 1 2 4]
['apple' 'banana' 'cherry']
['false' 'true' 'true']


In [4]:
#sorting a 2D array
import numpy as np
arr=np.array([[1,4,3],[7,5,8]])
print(np.sort(arr))

[[1 3 4]
 [5 7 8]]


In [8]:
#numpy array filtering means geeting some elements out of
# an existing array and creating a new array out of them
#we use boolean index list, it is the list of booleans
# corresponding to indexes in the array

#creating an array form elements on index 0 and 2
import numpy as np
arr=np.array([41,2,3,4])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)


[41  3]


In [10]:
#creating a filter array that will return 
# only values higher than 42
import numpy as np
arr=np.array([42,43,24,56,76])
#create an empty list
filter_arr=[]

#go through each element in arr
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
print(filter_arr)
newarr=arr[filter_arr]
print(newarr)

[False, True, False, True, True]
[43 56 76]


In [12]:
#creating a filter array that will 
# return only even elements from the original array
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
filter_arr=[]
for element in arr:
    if element%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
    
print(filter_arr)
newarr=arr[filter_arr]
print(newarr)

[False, True, False, True, False, True, False, True]
[2 4 6 8]


In [14]:
#creating filter directly from array
#create filter array higher than 42
import numpy as np
arr=np.array([41,42,43,45,67])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)
#for even
even=arr%2==0
newarray=arr[even]
print(even)
print(newarray)

[False False  True  True  True]
[43 45 67]
[False  True False False False]
[42]
